ft(server): user can sign up
atlp-rwanda/fan7-bn-backend pull request #13
Opened 2020-01-25 19:06 UTC by bihire

### What does this Pr do ?
A new User can signup new credentials in the API
### Description of the task to be completed ?
- save new credentials  saved in a postgres database
- return error if the credentials exists already
- run unit tests on the endpoint
- create user table if they don't exist already
- hash the saved password
- return error if inputs don't meet validation standards
- return token success

have the following endpoint work 
- POST /auth/signup
### How should this be manually tested?
after cloning this repository
- Using postman test the endpoint above

key: Content-type value: application/json
- generate a jwt token to put in headers as "token" by creating a new user

then send the following info
- {	
    "firstName": "",
    "lastName": "",
    "email": "",
    "password": "",
    "userName":"",
    "role": ""
  }
### Any background context you want to provide?
N/A
### What are the relevant pivot tracker stories ?
#170764576
https://www.pivotaltracker.com/story/show/170764576

### Any screenshots?
![image](https://user-images.githubusercontent.com/37307172/73125771-54a4be00-3fb3-11ea-8adf-027e3d124a27.png)
![image](https://user-images.githubusercontent.com/37307172/73126028-3f7d5e80-3fb6-11ea-9bed-087730ab5c2c.png)

2020-01-26 16:57 UTC, niyodusengaclement requested changes
This error should be handled first

2020-01-26 17:31 UTC, niyodusengaclement approved these changes
LGTM

2020-01-27 08:12 UTC, Elvis-rugamba commented on src/models/user.js
> +module.exports = (sequelize, DataTypes) => {
Could you use ES6?

2020-01-27 10:51 UTC, denislohan commented
@bihire  this coverage is not acceptable. it is below the line unless there is a good exlpaination
 the branch of 50 %, etc is very tiny. we agreed to have at least 80% coverage.

2020-01-27 13:06 UTC, ajimae approved these changes
LGTM!

2020-01-27 13:06 UTC, merged