#170764577 User account email verification
atlp-rwanda/fan7-bn-backend pull request #20
Opened 2020-01-30 15:43 UTC by Skemc

#### What does this PR do?
User can verify email after signup
#### Description of Task to be completed?
- User upon signUp receives a confirmation email
- After confirming through his email
- His approved in the database
- Added test
- Documented in swagger
#### How should this be manually tested?

- You have to clone the repo `git clone https://github.com/Stackup-Rwanda/fan7-bn-backend.git`
- Then After the repo cloned `cd project-folder` and run `npm i` to install all dependencies
- Go to my branch `git checkout ft-send-verification-email-170764577`
- Run app by `npm run dev`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170764577](https://www.pivotaltracker.com/story/show/170764577)
#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/53467315/73464432-93f25680-4387-11ea-9b38-3728e3d78b5c.png)
![image](https://user-images.githubusercontent.com/53467315/73464468-a8ceea00-4387-11ea-99a3-760b712c5db0.png)

#### Questions 
N/A

2020-01-30 16:13 UTC, shaazk requested changes
you're tests are failing, try to resolve all errors

2020-01-30 16:39 UTC, Elvis-rugamba requested changes
Work on your tests

2020-01-31 12:19 UTC, shaazk approved these changes

2020-01-31 12:20 UTC, Elvis-rugamba approved these changes

2020-01-31 12:23 UTC, ajimae approved these changes
LGTM!

2020-01-31 12:24 UTC, merged